### ISSUE TITLE
Currency Conversion

### ISSUE THREAD

**Issue by pdelamotar** [moneymanagerex/android-money-manager-ex#1498]
**Describe the bug**
Ammex does not do currency conversion in the dashboard

**To Reproduce**
1. Go to 'create account'
2. Set currency different from base currency 
3. Enter expenses or income

**Expected behavior**
Make the conversion to the base currency and then add it to the expenses/income 

**Device Information:**
 - Device: Samsung A24
 - OS: One UI 6.0 (ANDROID 14)
 - Cloud Storage: MEGA
 - App Version: 2024.01.05(1010)

**Additional context**
The software adds the expense/income to the total without doing the conversion in the dashboard

**Comment by Spoker** [comment]
I can confirm I have the same problem.

**Comment by bballmaster** [comment]
The other places this behavior shows itself are:

1. a "transfer" transaction. The amount in one of the fields you don't edit - withdrawal or deposit sum -  used to convert automatically according to exchange rate. Now the second field you don't edit is filled in, but as if the exchange rate is always 1:1, while it's not;
2. all reports also show numbers as if the exchange rate is always 1:1, while it's not.

The last release I used that didn't have this issue was [2019.02.14.994](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2019.02.14.994).

P.S.: thanks a lot for continuing to work of this extremely useful piece of software.

**Comment by guanlisheng** [comment]
this is fixed by https://github.com/moneymanagerex/android-money-manager-ex/pull/1621 and you can have a verification on latest apk via https://drive.google.com/file/d/1adbTNIsGBawEukogULl_Mppo2f2jAhCH/view?usp=sharing

**Comment by bballmaster** [comment]
Hi @guanlisheng!

Thanks for the fix.

I can confirm the "transfer" transaction case fixed - the fields for both accounts with different currencies are being filled up correctly considering exchange rate.

But the problem still stays for other descripted cases - all the reports just sum up values in different currencies without conversion. I checked it on my own DB and also created a new one to verify.

**Comment by guanlisheng** [comment]
this is weird as it works well in #1620

**Comment by bballmaster** [comment]
Sure. I reinstalled the app and started fresh to verify this case once again.

Here is my fresh example with a new DB created in AMMEX.

1. I use the up to date version - 2024.03.16 (1022).
![Screenshot_20240318_100529_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/18247879/a29c1ef9-0905-4876-8a54-5161ab3e96af)

2. The base currency is EUR.
![Screenshot_20240318_092114_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/18247879/dccb6cb5-9c4a-40f4-9c02-a2faf88a34f5)

3. The second currency is USD, and the exchange rate is 1 USD = 100 EUR -  just to make my example more obvious.
![Screenshot_20240318_092701_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/18247879/daef299f-8331-4a27-9aa9-d54dbb5dc393)

4. I have 2 accounts - one for each currency. And I made 2 transactions - for 1 USD and for 1 EUR. The home screen shows the right amount in sums, but wrong in both "Income vs Expenses" and "Where the money goes" reports.
![Screenshot_20240318_092528_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/18247879/c5b4e730-b8f2-47f0-96ea-0a1cac908370)
![Screenshot_20240318_092738_Money Manager Ex](https://github.com/moneymanagerex/android-money-manager-ex/assets/18247879/ce022fa3-5241-43bd-a04c-0cd3686a09e9)

I expect the reports not to sum the raw transaction amounts, but to convert the amounts to the base currency first - just like the desktop app does.
![image](https://github.com/moneymanagerex/android-money-manager-ex/assets/18247879/f248bc26-55ec-431e-b50e-2faa7254f787)

Here is the DB file.
[your_data.zip](https://github.com/moneymanagerex/android-money-manager-ex/files/14633005/your_data.zip)

Again: am I missing something?

**Comment by guanlisheng** [comment]
i c,  you should try the google Drive apk.  the fix is not released yet. sorry for the confusion. 


> This is fixed by #1621 and you can have a verification on the latest apk via https://drive.google.com/file/d/1adbTNIsGBawEukogULl_Mppo2f2jAhCH/view?usp=sharing

**Comment by guanlisheng** [comment]
sorry about the delay, we are trying to put the resource on sync, encryption, and feature parity
