### ISSUE TITLE
Latest version (2024.02.26) errors on editing 

### ISSUE THREAD

**Issue by robvinall** [moneymanagerex/android-money-manager-ex#1605]
**Describe the bug**
I updated to the latest version but if I tried to edit a current transaction it errors and does not save.

**To Reproduce**
1. Go to any current transaction and try to change the payee
2. Multiple errors when saving - cannot save. Have to revert.
3. Adding a new transaction is not affected 

**Expected behavior**
Should be able to edit old or recent transactions 

**Screenshots**

**Device Information:**
 - Device: [ Google pixel 7a]
 - OS: [e.g. Android 13]
 - Cloud Storage: [ Google drive]
 - App Version: [2024.02.26]

**Additional context**
Reverted back to version  2024.02.15 as this version does not have the issue.

**Comment by marcdw1289** [comment]
Can confirm issue with 2024.02.26.

Also, recurring transactions will apply but not change, thus constant prompting for the applied transactions.

**Comment by guanlisheng** [comment]
thanks @robvinall and @marcdw1289,  

i just addressed the issue and an incorrect conflictAlgorithm caused it during the insert and update.  will roll out an release shortly

**Comment by guanlisheng** [comment]
please try latest https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.03.07.1021

**Comment by marcdw1289** [comment]
Tested. Seems to be working well. Edits are working as before.

**Comment by robvinall** [comment]
Hi,
When will the updated F-Droid version be released? I previously downloaded
that release and it still doesn't have the last fixes I reported.

Regards

Rob

**Comment by guanlisheng** [comment]
f-droid needs about one week.
you can directly download from github https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2024.03.07.1021
