### ISSUE TITLE
Locale switch issues

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#203]
There are a couple of issues encountered when switching locales:

<s>1. There is no Bosnian language appearing in the list of supported languages.</s>
2. Switching to German changes the app theme in a weird way. Background does not match the foreground colors. 
<s>3. There is no Material Dark available in the selection menu, either. Theme_holo translation missing in de locale on crowdin.</s>
4. Open Currencies, graph, then go back, back, and the account group titles on dashboard are back in English.

Items missing because of missing locale support in Android Jelly Bean. On Lollipop it works fine.
<s>1. The dates in the list of recurring transactions (gray square) are in English.</s>
2. OK/Cancel on transaction edit are in English

I'll add more related issues here if I find them.

**Comment by MisterY** [comment]
Some strings are missing on Crowdin. Like theme_holo and Home. 
Any ideas?

**Comment by AlessandroLazzari** [comment]
Yes there are strings that I intentionally I felt could not be translated
as Holo, Material and I have hidden it in the Crowdin...according to you
can be translated?
These are the strings hidden

Money Manager Ex
Home
Material Dark
Material Light
None
Google Play In-App Billing
Donate
Dropbox
Dropbox - Money Manager Ex

**Comment by MisterY** [comment]
Well, try to change the theme in German. It is crazy! :D 
I didn't realize that was the setting. It says Theme_holo for Material Dark. However, the light theme is translated. I wonder where the strings are coming from. 

Home is needed as that is the title of the first item in the drawer. I tried to fix German translation (from 'Standad' to 'StandaRd') but it was not visible. Only switching to All Strings helped. 

I guess some of these should be visible. At least these two. Perhaps both themes.
This is the first time I'm testing in languages different than English.

**Comment by MisterY** [comment]
Yes, try to change the theme while using German to experience the weird styling issue, too. ;)

**Comment by AlessandroLazzari** [comment]
Ok then I make visible all the strings.

2015-04-20 22:16 GMT+02:00 Alen Siljak <notifications@github.com>:

**Comment by AlessandroLazzari** [comment]
Done!
​

**Comment by MisterY** [comment]
OK/Cancel are Android strings and Bosnian locale is not supported so there can be no auto-translation. Hopefully it is better for other languages.
Or should we switch to our strings instead of system?
action_button_cancel_done.xml, line 25

**Comment by AlessandroLazzari** [comment]
How ever is not supported for the bosnian? I thought that these strings
standard were translated for all languages...

**Comment by MisterY** [comment]
Hm, in the app I still see only OK and Cancel. In Android Studio, ctrl + click on "@android:string/cancel" gives me some list of locales but many are missing.

**Comment by MisterY** [comment]
It seems that the same goes for 
    new SimpleDateFormat("MMM", locale)
Meaning the missing languages will not get translated month abbreviations or dates in the Edit Transaction form.

**Comment by AlessandroLazzari** [comment]
In the dev branch was not past the locale in the object SimpleDateFormat
and had no problem. Now there are problems?

2015-04-20 23:09 GMT+02:00 Alen Siljak <notifications@github.com>:

**Comment by MisterY** [comment]
The same issue appears **with** and **without** passing the locale. With Bosnian settings, I see "May" as the name of the month.
The same for OK/Cancel buttons. None of these are words in Bosnian. Except, perhaps, OK.

**Comment by MisterY** [comment]
I'm concerned there might be other languages in the same situations and it looks ugly when part of the text is in English and another part in local language.
The big date in the Transaction Edit screen does the same. I guess it is the lack of support for minor languages in Android UI.

**Comment by AlessandroLazzari** [comment]
Ah ok, now i understood

**Comment by AlessandroLazzari** [comment]
I tried this:
"2. Switching to German changes the app theme in a weird way. The Background does not match the foreground colors. "
And the problem of graphics, it only happens if you change the language inside of our application, problem-very strange.

**Comment by MisterY** [comment]
So, the original question was if we should replace these system strings (ok/cancel) with our, translatable, versions.
While that would help for toolbar button translation, it would not help with the date translation (month name, day name). :(

**Comment by MisterY** [comment]
I assume there must be some colour name localized into German. :D

**Comment by MisterY** [comment]
Aaah, correction - on my phone the day/month names are correctly translated. It is only the Jelly Bean emulator where they are not!
On the phone I have 5.1.

**Comment by AlessandroLazzari** [comment]
Ok there is no problem.Depends or not if the location or not installed in the device.

**Comment by MisterY** [comment]
Only OK/Cancel buttons stay in English. I suggest we replace these with local strings. Should not be too much hassle.

**Comment by MisterY** [comment]
Ale, in German, the theme names are still Holo light and holo dark. That may be causing the problem with styling.

**Comment by MisterY** [comment]
The last assumption is correct. Related to #298.
The theme name is localized and (probably) later compared by name.

**Comment by MisterY** [comment]
Solved!
